[tool.kedro]
package_name = "betastar"
project_name = "betastar"
kedro_init_version = "0.19.10"
tools = "['Linting']"
example_pipeline = "False"
source_dir = "src"

[tool.ruff]
line-length = 88
show-fixes = true
select = [ "F", "W", "E", "I", "UP", "PL", "T201",]
ignore = [ "E501",]

[tool.ruff.format]
docstring-code-format = true

[tool.isort]
profile = "black"

[tool.setuptools.dynamic.version]
attr = "kedro_test.__version__"

[tool.setuptools.packages.find]
where = [ "src",]
namespaces = false
